<?php

use yii\base\Widget;
/**
 * Class ChatWidget
 *@package \common\widgets\chatWidget
 */
class ChatWidget extends Widget
{
    /**
     * @throws \yii\base\InvalidConfigExceptio
     */
    public function init()
    {
        ChatAsset::register($this->view);
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @return string
     */
    public function run()
    {
        if (\Yii::$app->user->isGuest) {
            $username = 'guest' . time();
        } else {
            $username = \Yii::$app->user->identity->username;
        }
        return $this->render('index', ['username' => $username]);
    }
}
